Web/Areas/Management/Controllers/SharedController.cs
using Entities.Models;
using Entities.ViewModels;
using Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Web.Areas.Management.Controllers
{
    [RouteArea("Management", AreaPrefix = "quan-ly")]
    [RoutePrefix("chia-se")]
    public class SharedController : Controller
    {
        IRepository _repository = DependencyResolver.Current.GetService<IRepository>();

        [Route("~/quan-ly/khong-co-quyen-truy-cap", Name = "SharedNoPermission")]
        [ActionName("NoPermission")]
        public ActionResult NoPermission()
        {
            return View();
        }
        [Route("~/quan-ly/loi-he-thong", Name = "ManagementGeneralError")]
        public ActionResult GeneralError()
        {
            ViewBag.Exception = TempData["Exception"];
            return View();
        }
        public List<Category> GetCategories(long? parentCategoryId, int level = 0, bool showPrefix = true)
        {
            List<Category> listCategory = new List<Category>();
            try
            {
                StringBuilder prefix = new StringBuilder();
                for (int i = 0; i < level; i++)
                {
                    prefix.Append("---");
                }
                var categories = _repository.GetRepository<Category>()
                    .GetAll(o => (parentCategoryId == null ? o.CategoryId == null : o.CategoryId == parentCategoryId) && (o.Link == null || o.Link == ""))
                    .OrderBy(o => o.OrdinalNumber).ToList<Category>();

                foreach (var item in categories)
                {
                    listCategory.Add(new Category
                    {
                        Id = item.Id,
                        Name = showPrefix == true ? (prefix.ToString() + " " + item.Name) : item.Name,
                        CategoryId = parentCategoryId
                    });
                    //Nếu có con thì gọi đệ quy
                    if (_repository.GetRepository<Category>().Any(o => o.CategoryId == item.Id))
                    {
                        listCategory.AddRange(GetCategories(item.Id, level + 1, showPrefix));
                    }
                }
                return listCategory;
            }
            catch
            {
                return listCategory;
            }
        }
        public List<CategoryToDropDownGroup> GetCategories2(int level = 0, bool showPrefix = true)
        {
            List<CategoryToDropDownGroup> listCategory = new List<CategoryToDropDownGroup>();
            try
            {
                StringBuilder prefix = new StringBuilder();
                for (int i = 0; i < level; i++)
                {
                    prefix.Append("---");
                }
                var categoryType = _repository.GetRepository<CategoryType>().GetAll().OrderBy(o => o.Name);
                if (categoryType != null && categoryType.Any())
                {
                    foreach (var item in categoryType)
                    {
                        var categories = _repository.GetRepository<Category>().GetAll(o => o.CategoryTypeId == item.Id).OrderBy(o => o.OrdinalNumber).ToList<Category>();
                        if (categories != null && categories.Any())
                        {
                            foreach (var item2 in categories)
                            {
                                listCategory.Add(new CategoryToDropDownGroup
                                {
                                    Id = item2.Id,
                                    Name = showPrefix == true ? (prefix.ToString() + " " + item2.Name) : item2.Name,
                                    CategoryId = null,
                                    CategoryTypeId = item.Id,
                                    CategoryTypeName = item.Name,
                                    OrdinalNumber = item2.OrdinalNumber
                                });
                                if (item2.Categories != null && item2.Categories.Any())
                                {
                                    listCategory.AddRange(GetCategories3(item2.Id, item.Id, item.Name, level + 1, showPrefix));
                                }
                            }
                        }
                    }
                }
                return listCategory;
            }
            catch
            {
                return listCategory;
            }
        }
        public List<CategoryToDropDownGroup> GetCategories3(long? parentCategoryId, long categpryTypeId, string categpryTypeName, int level = 0, bool showPrefix = true)
        {
            List<CategoryToDropDownGroup> listCategory = new List<CategoryToDropDownGroup>();
            try
            {
                StringBuilder prefix = new StringBuilder();
                for (int i = 0; i < level; i++)
                {
                    prefix.Append("---");
                }
                var categories = _repository.GetRepository<Category>()
                    .GetAll(o => (parentCategoryId == null ? o.CategoryId == null : o.CategoryId == parentCategoryId))
                    .OrderBy(o => o.OrdinalNumber).ToList<Category>();

                foreach (var item in categories)
                {
                    listCategory.Add(new CategoryToDropDownGroup
                    {
                        Id = item.Id,
                        Name = showPrefix == true ? (prefix.ToString() + " " + item.Name) : item.Name,
                        CategoryId = parentCategoryId,
                        CategoryTypeId = categpryTypeId,
                        CategoryTypeName = categpryTypeName,
                        OrdinalNumber = item.OrdinalNumber
                    });
                    //Nếu có con thì gọi đệ quy
                    if (item.Categories != null && item.Categories.Any())
                    {
                        listCategory.AddRange(GetCategories3(item.Id, categpryTypeId, categpryTypeName, level + 1, showPrefix));
                    }
                }
                return listCategory;
            }
            catch
            {
                return listCategory;
            }
        }
    }
}

Web/Controllers/LoginController.cs
using Common;
using Entities.Models;
using Entities.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
namespace Web.Controllers
{
    //[RoutePrefix("tai-khoan")]
    public class LoginController : BaseController
    {
        [Route("~/dang-nhap", Name = "FrontEndLoginIndex")]
        public ActionResult Index()
        {
            ViewBag.Error = TempData["Error"];
            ViewBag.Message = TempData["Message"];
            ViewBag.Success = TempData["Success"];
            ViewBag.Forget = TempData["Forget"];
            Session.Abandon();
            return View();
        }
        [Route("~/dang-nhap")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string email = StringHelper.KillChars(model.Email);
                    string password = StringHelper.StringToMd5(StringHelper.StringToMd5(StringHelper.KillChars(model.Password)).ToLower());
                    //var account = await _repository.GetRepository<Account>().ReadAsync(o => (o.Email == email && o.Password == password && o.IsNormalAccount == true && o.Profile != null));
                    var account = await _repository.GetRepository<Account>().ReadAsync(o => (o.Email == email && o.Password == password));
                    if (account == null)
                    {
                        ModelState.AddModelError(string.Empty, "Sai địa chỉ e-mail hoặc mật khẩu!");
                        //ViewBag.Error = "Sai địa chỉ e-mail hoặc mật khẩu!";
                        return View(model);
                    }
                    else
                    {
                        if (account.IsManageAccount && account.Profile == null)
                        {
                            Session["Email"] = account.Email;
                            Session["AccountId"] = account.Id;
                            Session["AccountName"] = account.Name;
                            Session["ProfilePicture"] = account.ProfilePicture;

                            var accountRoles = await _repository.GetRepository<AccountRole>().GetAllAsync(o => o.AccountId == account.Id);
                            var moduleRoles = await _repository.GetRepository<ModuleRole>().GetAllAsync();
                            CacheFactory _cacheFactory = new CacheFactory();
                            _cacheFactory.SaveCache("AccountRoles_" + account.Id, accountRoles.ToList());
                            _cacheFactory.SaveCache("ModuleRoles", moduleRoles.ToList());

                            return RedirectToRoute("ManagementHome");
                        }
                        if (account.Profile != null && account.Profile.Status != 2)
                        {//Nếu là tài khoản của cựu sinh viên mà chưa được duyệt hoặc chưa phân quyền thì không cho đăng nhập
                            ModelState.AddModelError(string.Empty, "Sai địa chỉ e-mail hoặc mật khẩu!");
                            return View(model);
                        }
                        Session["Email"] = account.Email;
                        Session["AccountId"] = account.Id;
                        Session["AccountName"] = account.Name;
                        Session["ProfilePicture"] = account.ProfilePicture;
                        Session["ProfileId"] = account.Profile.Id;
                        return RedirectToRoute("FrontEndProfileDetail");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Đã xảy ra lỗi: " + ex.Message);
                    //ViewBag.Error = "Đã có lỗi xảy ra: " + ex.Message;
                    return View(model);
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Vui lòng nhập đúng thông tin để đăng nhập!");
                //ViewBag.Error = "Vui lòng nhập đúng thông tin để đăng nhập!";
                return View(model);
            }
        }
        [Route("~/dang-xuat", Name = "FrontEndLoginLogout")]
        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToRoute("FrontEndHomeIndex");
        }
        [Route("~/quen-mat-khau-dang-nhap", Name = "FrontEndLoginForgetPassword")]
        public ActionResult ForgetPassword()
        {
            ViewBag.Success = TempData["Success"];
            return View();
        }
        [CaptchaMvc.Attributes.CaptchaVerify("Mã bảo mật không chính xác!")]
        [Route("~/quen-mat-khau-dang-nhap/")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgetPassword(ForgetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                string email = StringHelper.KillChars(model.Email);
                var account = await _repository.GetRepository<Account>().ReadAsync(o => o.Email == email);
                if (account == null)
                {
                    ModelState.AddModelError(string.Empty, "Địa chỉ email không tồn tại!");
                    return View(model);
                }
                else
                {
                    string activeCode = StringHelper.CreateRandomString(32);
                    activeCode = StringHelper.StringToMd5(activeCode).ToLower();
                    var temporaryPassword = StringHelper.CreateRandomString(8);

                    ForgetPassword forgetPassword = new Entities.Models.ForgetPassword();
                    forgetPassword.AccountId = account.Id;
                    forgetPassword.ActiveCode = activeCode;
                    forgetPassword.RequestTime = DateTime.Now;
                    forgetPassword.TemporaryPassword = Base64Hepler.EncodeTo64UTF8(StringHelper.StringToMd5(StringHelper.StringToMd5(StringHelper.KillChars(temporaryPassword)).ToLower()));
                    forgetPassword.Status = 0;
                    forgetPassword.RequestIp = CommonHelper.GetIPAddress(Request);
                    int result = await _repository.GetRepository<ForgetPassword>().CreateAsync(forgetPassword, account.Id);
                    var systemInfo = (await _repository.GetRepository<SystemInformation>().GetAllAsync()).FirstOrDefault();

                    if (result > 0 && systemInfo != null)
                    {
                        string domainName = Request.Url.Scheme + "://" + Request.Url.Authority;
                        StringBuilder body = new StringBuilder();
                        body.Append("Kính gửi " + StringHelper.KillChars(account.Name) + ",<br /><br />");
                        body.Append("Quí vị đã yêu cầu khôi phục mật khẩu trên website " + systemInfo.SiteName + "!<br />");
                        body.Append("Mật khẩu mới của quí vị là: " + temporaryPassword);
                        body.Append("<br />Quí vị vui lòng bấm ");
                        body.Append("<a href=\"" + domainName + "/xac-nhan-khoi-phuc-mat-khau/" + activeCode + "\" target=\"_blank\">vào đây</a>");
                        body.Append(" để xác thực việc quên mật khẩu. <br />");
                        body.Append(" Yêu cầu của quí vị chỉ có hiệu lực trong 24 giờ. <br />");
                        body.Append("<br /><br />Vô cùng xin lỗi nếu email này làm phiền quí vị!<br /><br />");
                        body.Append("<br />Kính thư, <br /><br />");
                        body.Append(systemInfo.SiteName + "<br />");
                        body.Append("Phát triển bởi eBtech Team<br />");
                        body.Append("Webmaster: quochuy7it@gmail.com");

                        bool result2 = await SendEmail.SendAsync(systemInfo.SMTPName, systemInfo.SMTPEmail, systemInfo.SMTPPassword, email, "Xác nhận khôi phục mật khẩu", body.ToString());
                        if (!result2)
                        {//Gửi email không thành công
                            forgetPassword.Status = 4;
                            int result1 = await _repository.GetRepository<ForgetPassword>().UpdateAsync(forgetPassword, account.Id);
                            ModelState.AddModelError(string.Empty, "Đã xảy ra lỗi khi thực hiện yêu cầu của bạn! (không gửi được email)");
                            return View(model);
                        }
                        else
                        {
                            TempData["Success"] = true;
                            return RedirectToRoute("FrontEndLoginForgetPassword");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Vui lòng nhập đầy đủ các thông tin!");
                        return View(model);
                    }
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Vui lòng nhập đầy đủ các thông tin!");
                return View(model);
            }
        }
        /// <summary>
        /// Xác nhận yêu cầu mật khẩu mới
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        [Route("~/xac-nhan-khoi-phuc-mat-khau/{code?}")]
        public async Task<ActionResult> ConfirmPassword(string code)
        {
            try
            {
                ViewBag.Message = "";
                var forgetPassword = await _repository.GetRepository<ForgetPassword>().ReadAsync(o => o.ActiveCode == code);
                if (forgetPassword == null)
                {
                    ViewBag.Message = "Yêu cầu của bạn không chính xác. Vui lòng kiểm tra lại!";
                    return View();
                }
                else
                {
                    if (forgetPassword.Status != 0)

Web/Views/Login/ForgetPassword.cshtml
@model Entities.ViewModels.ForgetPasswordViewModel
@using CaptchaMvc.HtmlHelpers
@using CaptchaMvc.Interface
@{
    ViewBag.Title = "Quên mật khẩu";
    Layout = "~/Views/Shared/_DetailLayout.cshtml";
    ICaptcha captcha = Html.Captcha("Đổi mã khác", "Nhập mã bảo mật phía trên:", 5, "Vui lòng nhập mã bảo mật!", false);
    bool success = false;
    if (ViewBag.Success != null) { success = (bool)ViewBag.Success; }
}

<div class="content">
    <div class="left_detail">
        <h2>Quên mật khẩu</h2>
        <div class="clear"></div>
        <div class="row">
            <div class="col-md-12 form">
                @if (success)
                {
                    <div>
                        Chúng tôi đã nhận yêu cầu lấy lại mật khẩu của quí vị. 
                        <br />Quí vị vui lòng kiểm tra email và làm theo hướng dẫn!
                    </div>
                }
                else
                {
                    using (Html.BeginForm("ForgetPassword", "Login", FormMethod.Post, new { @class = "login-form form-horizontal" }))
                    {
                        <div class="form-body">
                            <div class="note note-success">
                                <p>Quí vị vui lòng nhập địa chỉ email để lấy mật khẩu mới.</p>
                                <p>Mật khẩu mới sẽ được gửi qua email và có hiệu lực trong vòng 24h từ lúc quí vị yêu cầu.</p>
                            </div>
                            @Html.AntiForgeryToken()
                            @if (!ViewData.ModelState.IsValid)
                            {
                                <div class="alert alert-danger">
                                    <button class="close" data-dismiss="alert"></button>
                                    @Html.ValidationSummary(true)
                                </div>
                            }
                            <div class="form-group">
                                @Html.LabelFor(model => model.Email, new { @class = "col-md-3 control-label" })
                                <div class="col-md-4">
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Email)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Mã bảo mật</label>
                                <div class="col-md-4">
                                    @captcha.RenderMarkup()
                                    @Html.ValidationMessage("CaptchaInputText")
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-4">
                                    <button type="submit" class="btn green-haze pull-right">
                                        Gửi đi <i class="m-icon-swapright m-icon-white"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <div class="right_detail">
        @{Html.RenderAction("MostViewed2", "Shared");}
    </div>
    <div class="clear"></div>
</div>
@section styles{
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/components")
    @Styles.Render("~/Content/plugins")
    @Styles.Render("~/Content/font-awesome")
    @Styles.Render("~/Content/custom")
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        jQuery(document).ready(function () {
            $('#CaptchaInputText').addClass('form-control');
            $('#email_forget').focus();
        });
    </script>
    @captcha.RenderScript()
}

Web/Views/Login/Index.cshtml
@model Entities.ViewModels.LoginViewModel
@{
    ViewBag.Title = "Đăng nhập";
    Layout = "~/Views/Shared/_DetailLayout.cshtml";
}

<div class="content">
    <div class="left_detail">
        <h2>Đăng nhập</h2>
        <div class="clear"></div>
        <div class="row">
            <div class="col-md-12 form">
                @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "login-form form-horizontal" }))
                {
                    <div class="form-body">
                        @Html.AntiForgeryToken()
                        @if (!ViewData.ModelState.IsValid)
                        {
                        <div class="alert alert-danger">
                            <button class="close" data-dismiss="alert"></button>
                            @Html.ValidationSummary(true)
                        </div>
                        }
                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, new { @class = "col-md-3 control-label" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Email)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, new { @class = "col-md-3 control-label" })
                            <div class="col-md-4">
                                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Password)
                            </div>
                        </div>
                        <div class="forget-password">
                            <h4>Quên mật khẩu?</h4>
                            <p>
                                Bấm <a href="@Url.RouteUrl("FrontEndLoginForgetPassword")">
                                    vào đây
                                </a>
                                để khôi phục mật khẩu.
                            </p>
                        </div>
                    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-4">
                <button type="submit" class="btn green-haze pull-right">
                    Đăng nhập <i class="m-icon-swapright m-icon-white"></i>
                </button>
            </div>
        </div>
    </div>
                }
                    </div>
        </div>
    </div>
    <div class="right_detail">
        @{Html.RenderAction("MostViewed2", "Shared");}
    </div>
    <div class="clear"></div>
</div>
@section styles{
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/components")
    @Styles.Render("~/Content/plugins")
    @Styles.Render("~/Content/font-awesome")
    @Styles.Render("~/Content/custom")
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}