Web/Areas/Management/Controllers/ImportController.cs
using Common;
using Entities.Enums;
using Entities.Models;
using Entities.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Web.Areas.Management.Filters;
using Web.Areas.Management.Helpers;
using Web.Helpers;
using System.Transactions;

namespace Web.Areas.Management.Controllers
{
    [RouteArea("Management", AreaPrefix = "quan-ly")]
    [RoutePrefix("quan-ly-du-lieu")]
    public class ImportController : BaseController
    {
        [Route("import-du-lieu", Name = "ImportIndex")]
        [ValidationPermission(Action = ActionEnum.Read, Module = ModuleEnum.Import)]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// import
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("import-nha-modal", Name = "ImportNhaModal")]
        public async Task<ActionResult> ImportNha()
        {

            return PartialView("ImportNhaModal");
        }

        [HttpPost]
        [Route("import-nha")]
        public ActionResult ImportNha(HttpPostedFileBase uploadFile)
        {
            StringBuilder strValidations = new StringBuilder(string.Empty);
            try
            {
                if (uploadFile.ContentLength > 0)
                {
                    string filePath = Path.Combine(HttpContext.Server.MapPath("/Uploads/files"), Path.GetFileName(uploadFile.FileName));
                    uploadFile.SaveAs(filePath);
                    DataSet ds = new DataSet();

                    string ConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties=Excel 12.0;";

                    using (OleDbConnection conn = new System.Data.OleDb.OleDbConnection(ConnectionString))
                    {
                        conn.Open();
                        using (DataTable dtExcelSchema = conn.GetSchema("Tables"))
                        {
                            string sheetName = "Data$";
                            string query = "SELECT * FROM [" + sheetName + "]";
                            OleDbDataAdapter adapter = new OleDbDataAdapter(query, conn);
                            adapter.Fill(ds, "Items");
                            if (ds.Tables.Count > 0)
                            {
                                if (ds.Tables[0].Rows.Count > 0)
                                {
                                    Nha nha = new Nha();
                                    //fdsfdsf
                                    int resultCount = 0;
                                    int recordExcelCount = ds.Tables[0].Rows.Count;

                                    using (TransactionScope tscope = new TransactionScope())
                                    {
                                        foreach (DataRow r in ds.Tables[0].Rows)
                                        {
                                            string matBang = Convert.ToString(r["Mặt bằng"]);
                                            long matBangId = (_repository.GetRepository<MatBang>().Read(o => o.Name == matBang)) != null ? (_repository.GetRepository<MatBang>().Read(o => o.Name == matBang)).Id : 0;

                                            string quan = Convert.ToString(r["Quận"]);
                                            long quanId = (_repository.GetRepository<Quan>().Read(o => o.Name == quan)).Id;

                                            string duong = Convert.ToString(r["Đường"]);
                                            long duongId = (_repository.GetRepository<Duong>().Read(o => o.Name == duong)).Id;

                                            string noiThatKhachThueCu = Convert.ToString(r["Nội thất khách thuê cũ"]);
                                            long noiThatKhachThueCuId = (_repository.GetRepository<NoiThatKhachThueCu>().Read(o => o.Name == noiThatKhachThueCu)) != null ? (_repository.GetRepository<NoiThatKhachThueCu>().Read(o => o.Name == noiThatKhachThueCu)).Id : 1;


                                            string danhGiaPhuHopVoi = Convert.ToString(r["Đánh giá phù hợp với"]);
                                            long danhGiaPhuHopVoiId = (_repository.GetRepository<DanhGiaPhuHopVoi>().Read(o => o.Name == danhGiaPhuHopVoi)) != null ?(_repository.GetRepository<DanhGiaPhuHopVoi>().Read(o => o.Name == danhGiaPhuHopVoi)).Id : 0;

                                            string capDoTheoDoi = Convert.ToString(r["Cấp độ theo dõi"]);
                                            int capDoTheoDoiId = (_repository.GetRepository<CapDoTheoDoi>().Read(o => o.Name == capDoTheoDoi)) != null? (_repository.GetRepository<CapDoTheoDoi>().Read(o => o.Name == capDoTheoDoi)).Id : 1;

                                            nha.MatBangId = matBangId == 0 ? null : Convert.ToString(matBangId);
                                            nha.QuanId = quanId;
                                            nha.DuongId = duongId;
                                            nha.SoNha = r["Số nhà"] == DBNull.Value ? "" : r["Số nhà"].ToString();
                                            nha.TenToaNha = r["Tên toàn nhà"] == DBNull.Value ? "" : (string)r["Tên toàn nhà"];
                                            nha.MatTienTreoBien = r["Mặt tiền treo biển"] == DBNull.Value ? 0 : float.Parse(r["Mặt tiền treo biển"].ToString());
                                            nha.BeNgangLotLong = r["Bề ngang lọt lòng"] == DBNull.Value ? 0 : float.Parse(r["Bề ngang lọt lòng"].ToString());
                                            nha.DienTichDat = r["Diện tích đất"] == DBNull.Value ? 0 : float.Parse(r["Diện tích đất"].ToString());
                                            nha.DienTichDatSuDungTang1 = r["Diện tích đất sử dụng tầng 1"] == DBNull.Value ? 0 : float.Parse(r["Diện tích đất sử dụng tầng 1"].ToString());
                                            nha.SoTang = r["Số tầng"] == DBNull.Value ? 0 : int.Parse(r["Số tầng"].ToString());
                                            nha.TongDienTichSuDung = r["Tổng diện tích sử dụng"] == DBNull.Value ? 0 : int.Parse(r["Tổng diện tích sử dụng"].ToString());
                                            nha.DiChungChu = (string)r["Đi chung chủ"] == "Có" ? true : false;
                                            nha.Ham = (string)r["Hầm"] == "Có" ? true : false;
                                            nha.ThangMay = (string)r["Thang máy"] == "Có" ? true : false;
                                            nha.NoiThatKhachThueCuId = noiThatKhachThueCuId;
                                            nha.DanhGiaPhuHopVoiId = danhGiaPhuHopVoiId == 0? null : Convert.ToString(danhGiaPhuHopVoiId);
                                            nha.TongGiaThue = r["Tổng giá thuê"] == DBNull.Value ? 0 : decimal.Parse(r["Tổng giá thuê"].ToString());
                                            nha.GiaThueBQ = r["Giá thuê BQ"] == DBNull.Value ? 0 : decimal.Parse(r["Giá thuê BQ"].ToString());
                                            nha.TenNguoiLienHeVaiTro = r["Tên người liên hệ - vai trò"] == DBNull.Value ? "" : (string)r["Tên người liên hệ - vai trò"];
                                            nha.SoDienThoai = r["Số điện thoại"] == DBNull.Value ? "" : r["Số điện thoại"].ToString();
                                            nha.NgayCNHenLienHeLai = r["Ngày CN hẹn liên hệ lại"] == DBNull.Value ? (DateTime?)null : Convert.ToDateTime(r["Ngày CN hẹn liên hệ lại"]);
                                            nha.CapDoTheoDoiId = capDoTheoDoiId;
                                            nha.GhiChu = r["Ghi chú"] == DBNull.Value ? "" : (string)r["Ghi chú"];
                                            nha.NgayTao = DateTime.Now;
                                            nha.NguoiTaoId = AccountId;
                                            nha.TrangThai = 0; //Chờ duyệt

                                            int result = 0;
                                            try
                                            {
                                                result = _repository.GetRepository<Nha>().Create(nha, AccountId);
                                            }
                                            catch { }
                                            if (result > 0)
                                            {
                                                resultCount++;
                                            }

                                        }

                                        if (resultCount == recordExcelCount)
                                        {
                                            tscope.Complete();

                                            TempData["Success"] = "Import dữ liệu thành công!";

                                            return RedirectToAction("Index");
                                        }
                                        else
                                        {
                                            Transaction.Current.Rollback();
                                            tscope.Dispose();

                                            TempData["Error"] = "Import dữ liệu không thành công, vui lòng thử lại!";
                                            return RedirectToAction("Index");
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {

Web/Areas/Management/Views/Import/ImportKhachModal.cshtml
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">Import dữ liệu khách</h4>
</div>
<div class="modal-body">
    <div class="row">
        @using (Html.BeginForm("ImportKhach", "Import", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal form-bordered form-row-stripped" }))
        {
            <div style="display: flex; margin: 10px 10px 10px 20px">
                <input id="uploadFile" name="uploadFile" type="file" style="margin-right: 68px;" />
                <input type="submit" value="UploadFile" title="Upload file" onclick="return CheckFileName();" />
            </div>
        }
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">Đóng lại</button>
</div>
<script type="text/javascript">
    function CheckFileName() {
        var fileName = document.getElementById("uploadFile").value;
        if (fileName == "") {
            alert("Bạn chưa chọn file.");
            return false;
        }
        else if (fileName.split(".")[1].toUpperCase() == "XLS" || fileName.split(".")[1].toUpperCase() == "XLSX")
            return true;
        else {
            alert("Không hỗ trợ định dạng file " + fileName.split(".")[1] + ". Vui lòng chỉ upload file có định dạng xls / xlsx");
            return false;
        }
        return true;
    }
</script>

<style type="text/css">
    .modal-dialog {
        width: 680px;
    }

    .static-info {
        margin-bottom: 10px;
    }
</style>

Web/Areas/Management/Views/Import/ImportNhaModal.cshtml
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">Import dữ liệu nhà</h4>
</div>
<div class="modal-body">
    <div class="row">
        @using (Html.BeginForm("ImportNha", "Import", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal form-bordered form-row-stripped" }))
        {
            <div style="display: flex; margin: 10px 10px 10px 20px">
                <input id="uploadFile" name="uploadFile" type="file" style="margin-right: 68px;" />
                <input type="submit" value="UploadFile" title="Upload file" onclick="return CheckFileName();" />
            </div>
        }
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">Đóng lại</button>
</div>
<script type="text/javascript">
    function CheckFileName() {
        var fileName = document.getElementById("uploadFile").value;
        if (fileName == "") {
            alert("Bạn chưa chọn file.");
            return false;
        }
        else if (fileName.split(".")[1].toUpperCase() == "XLS" || fileName.split(".")[1].toUpperCase() == "XLSX")
            return true;
        else {
            alert("Không hỗ trợ định dạng file " + fileName.split(".")[1] + ". Vui lòng chỉ upload file có định dạng xls / xlsx");
            return false;
        }
        return true;
    }
</script>

<style type="text/css">
    .modal-dialog {
        width: 680px;
    }

    .static-info {
        margin-bottom: 10px;
    }
</style>

Web/Areas/Management/Views/Import/Index.cshtml
@using Entities.Enums;
@{
    ViewBag.Title = "Import dữ liệu";
    Layout = "~/Areas/Management/Views/Shared/_ManagementLayout.cshtml";
}
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.RouteUrl("ManagementHome")">Trang chủ</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="javascript:void(0);">Import</a>
        </li>
    </ul>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="portlet light">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-check-square font-green-sharp bold"></i>
                    <span class="caption-subject font-green-sharp bold ">Import dữ liệu</span>
                </div>

            </div>
            <div class="portlet-body">
                <div class="alert-box warning">
                    <span><i class="fa fa-warning"></i> Chú ý: </span>Yêu cầu bắt buộc để import dữ liệu là file import phải đúng template. Vui lòng tải teamplate tại đây:<br />
                    <div style="margin-left: 45px; font-weight: bold;">
                        <i class="fa fa-download"></i><a href="~/Template/ImportKhach_Template.xlsx"> Template import dữ liệu khách</a><br />
                        <i class="fa fa-download"></i><a href="~/Template/ImportNha_Template.xlsx"> Template import dữ liệu nhà</a>
                        <p style="color: red">Hãy nhập đủ những trường bắt buộc ( Có tiêu đề màu đỏ trong file Template )</p>
                    </div>
                </div>
                <a class="btn btn-xs blue btn-import" href="@Url.RouteUrl("ImportNhaModal")" data-target="#ajaxmodal" data-toggle="modal"><i class="fa fa-share"></i> Import dữ liệu nhà</a>
                <a class="btn btn-xs blue btn-import" href="@Url.RouteUrl("ImportKhachModal")" data-ta data-target="#ajaxmodal" data-toggle="modal"><i class="fa fa-share"></i> Import dữ liệu khách</a>
            </div>
        </div>
    </div>
</div>

<style>
    .alert-box {
        color: #555;
        padding: 10px 10px 10px 36px;
        margin-bottom: 20px;
    }

        .alert-box span {
            font-weight: bold;
            text-transform: uppercase;
        }

    .warning {
        background-color: #fff8c4;
        border: 1px solid #f2c779;
    }

    .btn-import {
        padding: 10px;
        margin-right: 10px;
    }
</style>