Web/Areas/Management/Controllers/SharedController.cs
using Entities.Models;
using Entities.ViewModels;
using Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Web.Areas.Management.Controllers
{
    [RouteArea("Management", AreaPrefix = "quan-ly")]
    [RoutePrefix("chia-se")]
    public class SharedController : Controller
    {
        IRepository _repository = DependencyResolver.Current.GetService<IRepository>();

        [Route("~/quan-ly/khong-co-quyen-truy-cap", Name = "SharedNoPermission")]
        [ActionName("NoPermission")]
        public ActionResult NoPermission()
        {
            return View();
        }
        [Route("~/quan-ly/loi-he-thong", Name = "ManagementGeneralError")]
        public ActionResult GeneralError()
        {
            ViewBag.Exception = TempData["Exception"];
            return View();
        }
        public List<Category> GetCategories(long? parentCategoryId, int level = 0, bool showPrefix = true)
        {
            List<Category> listCategory = new List<Category>();
            try
            {
                StringBuilder prefix = new StringBuilder();
                for (int i = 0; i < level; i++)
                {
                    prefix.Append("---");
                }
                var categories = _repository.GetRepository<Category>()
                    .GetAll(o => (parentCategoryId == null ? o.CategoryId == null : o.CategoryId == parentCategoryId) && (o.Link == null || o.Link == ""))
                    .OrderBy(o => o.OrdinalNumber).ToList<Category>();

                foreach (var item in categories)
                {
                    listCategory.Add(new Category
                    {
                        Id = item.Id,
                        Name = showPrefix == true ? (prefix.ToString() + " " + item.Name) : item.Name,
                        CategoryId = parentCategoryId
                    });
                    //Nếu có con thì gọi đệ quy
                    if (_repository.GetRepository<Category>().Any(o => o.CategoryId == item.Id))
                    {
                        listCategory.AddRange(GetCategories(item.Id, level + 1, showPrefix));
                    }
                }
                return listCategory;
            }
            catch
            {
                return listCategory;
            }
        }
        public List<CategoryToDropDownGroup> GetCategories2(int level = 0, bool showPrefix = true)
        {
            List<CategoryToDropDownGroup> listCategory = new List<CategoryToDropDownGroup>();
            try
            {
                StringBuilder prefix = new StringBuilder();
                for (int i = 0; i < level; i++)
                {
                    prefix.Append("---");
                }
                var categoryType = _repository.GetRepository<CategoryType>().GetAll().OrderBy(o => o.Name);
                if (categoryType != null && categoryType.Any())
                {
                    foreach (var item in categoryType)
                    {
                        var categories = _repository.GetRepository<Category>().GetAll(o => o.CategoryTypeId == item.Id).OrderBy(o => o.OrdinalNumber).ToList<Category>();
                        if (categories != null && categories.Any())
                        {
                            foreach (var item2 in categories)
                            {
                                listCategory.Add(new CategoryToDropDownGroup
                                {
                                    Id = item2.Id,
                                    Name = showPrefix == true ? (prefix.ToString() + " " + item2.Name) : item2.Name,
                                    CategoryId = null,
                                    CategoryTypeId = item.Id,
                                    CategoryTypeName = item.Name,
                                    OrdinalNumber = item2.OrdinalNumber
                                });
                                if (item2.Categories != null && item2.Categories.Any())
                                {
                                    listCategory.AddRange(GetCategories3(item2.Id, item.Id, item.Name, level + 1, showPrefix));
                                }
                            }
                        }
                    }
                }
                return listCategory;
            }
            catch
            {
                return listCategory;
            }
        }
        public List<CategoryToDropDownGroup> GetCategories3(long? parentCategoryId, long categpryTypeId, string categpryTypeName, int level = 0, bool showPrefix = true)
        {
            List<CategoryToDropDownGroup> listCategory = new List<CategoryToDropDownGroup>();
            try
            {
                StringBuilder prefix = new StringBuilder();
                for (int i = 0; i < level; i++)
                {
                    prefix.Append("---");
                }
                var categories = _repository.GetRepository<Category>()
                    .GetAll(o => (parentCategoryId == null ? o.CategoryId == null : o.CategoryId == parentCategoryId))
                    .OrderBy(o => o.OrdinalNumber).ToList<Category>();

                foreach (var item in categories)
                {
                    listCategory.Add(new CategoryToDropDownGroup
                    {
                        Id = item.Id,
                        Name = showPrefix == true ? (prefix.ToString() + " " + item.Name) : item.Name,
                        CategoryId = parentCategoryId,
                        CategoryTypeId = categpryTypeId,
                        CategoryTypeName = categpryTypeName,
                        OrdinalNumber = item.OrdinalNumber
                    });
                    //Nếu có con thì gọi đệ quy
                    if (item.Categories != null && item.Categories.Any())
                    {
                        listCategory.AddRange(GetCategories3(item.Id, categpryTypeId, categpryTypeName, level + 1, showPrefix));
                    }
                }
                return listCategory;
            }
            catch
            {
                return listCategory;
            }
        }
    }
}

Web/Controllers/ArticleController.cs
using Common;
using Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
namespace Web.Controllers
{
    //[RoutePrefix("bai-viet")]
    public class ArticleController : BaseController
    {
        /// <summary>
        /// Chi tiết bài viết
        /// </summary>
        /// <param name="title"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("~/{categoryName}/{title}/{categoryId}/{id}", Name = "FrontEndArticleDetail")]
        public async Task<ActionResult> Detail(string categoryName, string title, long categoryId, long id)
        {
            Category category = await _repository.GetRepository<Category>().ReadAsync(categoryId);
            Category rootCategory = new SharedController().GetRootCategory(category);
            ViewBag.RootCategory = rootCategory;
            ViewBag.CategoryId = categoryId;
            ViewBag.Category = category;
            var article = _repository.GetRepository<Article>().Read(id);
            if(article.Status!=4)
            {
                return RedirectToRoute("FrontEndHomeIndex");
            }
            article.Views = article.Views + 1;
            try
            {
                await _repository.GetRepository<Article>().UpdateAsync(article, 0);
            }
            catch { }
            return View(article);
        }
        [Route("~/bai-viet/{title}/{id}", Name = "FrontEndArticleDetail2")]
        public async Task<ActionResult> Detail(string title, long id)
        {
            var articleCategory = await _repository.GetRepository<ArticleCategory>().ReadAsync(o => o.ArticleId == id);
            if (articleCategory != null)
            {
                Category category = await _repository.GetRepository<Category>().ReadAsync(articleCategory.CategoryId);
                Category rootCategory = new SharedController().GetRootCategory(category);
                ViewBag.RootCategory = rootCategory;
                ViewBag.CategoryId = articleCategory.CategoryId;
                ViewBag.Category = category;
            }
            var article = _repository.GetRepository<Article>().Read(id);
            if (article.Status != 4)
            {
                return RedirectToRoute("FrontEndHomeIndex");
            }
            article.Views = article.Views + 1;
            try
            {
                await _repository.GetRepository<Article>().UpdateAsync(article, 0);
            }
            catch { }
            return View(article);
        }
        ///// <summary>
        ///// Danh sách bản tin theo chuyên mục
        ///// </summary>
        ///// <param name="title"></param>
        ///// <param name="categoryId"></param>
        ///// <returns></returns>
        //[Route("~/chuyen-muc/{categoryName}/{categoryId}/{p?}", Name = "FrontEndArticleIndex")]
        //public async Task<ActionResult> Index(string categoryName, long categoryId, int p = 1)
        //{
        //    Category category = await _repository.GetRepository<Category>().ReadAsync(categoryId);
        //    ViewBag.Category = category;
        //    if (category.CategoryId == null && category.DisplayType.HasValue && category.DisplayType.Value == 2)
        //    {
        //        List<Category> categories = new List<Category>();
        //        if (category.Categories != null && category.Categories.Any())
        //        {
        //            foreach (var item in category.Categories.OrderBy(o => o.OrdinalNumber))
        //            {
        //                if (item.Categories != null && item.Categories.Any())
        //                {
        //                    categories.AddRange(item.Categories.OrderBy(o => o.OrdinalNumber));
        //                }
        //            }
        //        }
        //        return View("Category", categories);
        //    }
        //    Category rootCategory = new SharedController().GetRootCategory(category);
        //    ViewBag.CategoryName = category.Name;
        //    ViewBag.RootCategory = rootCategory;
        //    ViewBag.CategoryId = categoryId;

        //    int take = 20;
        //    int skip = (p - 1) * take;
        //    var articles = _repository.GetRepository<Article>().GetAll(o => o.Status == 4)
        //          .Join(_repository.GetRepository<ArticleCategory>().GetAll(o => o.CategoryId == categoryId), b => b.Id, c => c.ArticleId, (b, c) => new { Article = b }).Select(x => x.Article).ToList<Article>();
        //    if (articles == null || articles.AsQueryable().Count() == 0)
        //    {
        //        var categoryIds = GetChildCategoryIds(rootCategory);
        //        articles = _repository.GetRepository<Article>().GetAll(o => o.Status == 4)
        //          .Join(_repository.GetRepository<ArticleCategory>().GetAll(o => categoryIds.Contains(o.CategoryId)), b => b.Id, c => c.ArticleId, (b, c) => new { Article = b }).Select(x => x.Article).ToList<Article>();
        //    }
        //    ViewBag.PagingInfo = new PagingInfo
        //    {
        //        CurrentPage = p,
        //        ItemsPerPage = take,
        //        TotalItems = articles.AsQueryable().Count()
        //    };
        //    articles = articles.Skip(skip).Take(take).ToList();



        //    return View(articles);
        //}
        /// <summary>
        /// Danh sách bản tin theo chuyên mục
        /// </summary>
        /// <param name="title"></param>
        /// <param name="categoryId"></param>
        /// <returns></returns>
        [Route("~/chuyen-muc/{categoryName}/{categoryId}/{p?}", Name = "FrontEndArticleIndex")]
        public async Task<ActionResult> Index(string categoryName, long categoryId, int p = 1)
        {
            Category category = await _repository.GetRepository<Category>().ReadAsync(categoryId);
            Category rootCategory = new SharedController().GetRootCategory(category);
            ViewBag.CategoryName = category.Name;
            ViewBag.RootCategory = rootCategory;
            ViewBag.CategoryId = categoryId;
            ViewBag.Category = category;

            if (category.CategoryId == null && category.DisplayType.HasValue &&
                (category.DisplayType.Value == 1 || category.DisplayType.Value == 3 || category.DisplayType.Value == 5))
            {
                if (category.DisplayType.Value == 5)
                {
                    List<Category> categories = new List<Category>();
                    if (category.Categories != null && category.Categories.Any())
                    {
                        foreach (var item in category.Categories.OrderBy(o => o.OrdinalNumber))
                        {
                            if (item.Categories != null && item.Categories.Any())
                            {
                                categories.AddRange(item.Categories.OrderBy(o => o.OrdinalNumber));
                            }
                        }
                    }
                    return View("Category5", categories);
                }
                if (category.DisplayType.Value == 1)
                    return View("Category1");//Không cần sanh sách bài viết
                if (category.DisplayType.Value == 3)
                    return View("Category3");//Không cần sanh sách bài viết
            }

            int take = 12;
            int skip = (p - 1) * take;
            var articles = _repository.GetRepository<Article>().GetAll(o => o.Status == 4)
                  .Join(_repository.GetRepository<ArticleCategory>().GetAll(o => o.CategoryId == categoryId), b => b.Id, c => c.ArticleId, (b, c) => new { Article = b }).Select(x => x.Article)
                  .OrderByDescending(o => o.UpdateDate).ToList<Article>();
            if (articles == null || articles.AsQueryable().Count() == 0)
            {
                //var categoryIds = GetChildCategoryIds(rootCategory);
                var categoryIds = GetChildCategoryIds(category);
                articles = _repository.GetRepository<Article>().GetAll(o => o.Status == 4)
                  .Join(_repository.GetRepository<ArticleCategory>().GetAll(o => categoryIds.Contains(o.CategoryId)), b => b.Id, c => c.ArticleId, (b, c) => new { Article = b }).Select(x => x.Article)
                  .OrderByDescending(o => o.UpdateDate).ToList<Article>();
            }
            ViewBag.PagingInfo = new PagingInfo
            {
                CurrentPage = p,
                ItemsPerPage = take,
                TotalItems = articles.AsQueryable().Count()
            };
            articles = articles.OrderByDescending(o => o.UpdateDate).Skip(skip).Take(take).ToList();

            if (category.CategoryId == null && category.DisplayType.HasValue && category.DisplayType.Value == 2)
                return View("Category2", articles);
            if (category.CategoryId == null && category.DisplayType.HasValue && category.DisplayType.Value == 4)
                return View("Category4", articles);
            //return View(articles);//Bỏ cái này
            return View("Category2", articles);

        }
        public ActionResult ArticlesByCategory1(long categoryId)
        {
            Category category = _repository.GetRepository<Category>().Read(categoryId);
            ViewBag.Category = category;
            var categoryIds = GetChildCategoryIds(category);
            var model = new List<Article>();
            var articles = _repository.GetRepository<Article>().GetAll(o => o.Status == 4)
                  .Join(_repository.GetRepository<ArticleCategory>().GetAll(o => o.CategoryId == categoryId), b => b.Id, c => c.ArticleId, (b, c) => new { Article = b }).Select(x => x.Article)
                  .OrderByDescending(o => o.UpdateDate).Take(10).ToList<Article>();
            if (articles == null || articles.AsQueryable().Count() < 10)
            {
                int take = 0;

Web/Views/Article/Category1.cshtml
@using Common;
@using Entities.Models;
@{
    Category category = (Category)ViewBag.Category;
    Category rootCategory = (Category)ViewBag.RootCategory;
    ViewBag.Title = category.Name;
    Layout = "~/Views/Shared/_Layout_Category1.cshtml";

}

<div class="category-header">
    <div class="category-header-detail">
        <img src="@(string.IsNullOrEmpty(rootCategory.DescriptionIcon) ? " />Images/FrontEndV1/img_mainDetail.jpg" : rootCategory.DescriptionIcon)" alt="@rootCategory.Name" title="@rootCategory.Name" />
        @if (rootCategory != null && !rootCategory.IsNullOrEmpty)
        {
            <h2>@rootCategory.Name</h2>
        }
    </div>
</div>
<div class="category-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="@Url.RouteUrl("FrontEndHomeIndex")">Trang chủ</a>
                <i class="fa fa-angle-right"></i>
            </li>
            @if (rootCategory != null)
            {
                <li>
                    @if (string.IsNullOrEmpty(rootCategory.Link))
                    {
                        <a href="@Url.RouteUrl("FrontEndArticleIndex", new { categoryname = StringHelper.StringFilter(rootCategory.Name), categoryid = rootCategory.Id })">@rootCategory.Name</a>
                    }
                    else
                    {
                        <a href="@rootCategory.Link">@rootCategory.Name</a>
                    }
                    <i class="fa fa-angle-right"></i>
                </li>
            }
            @if (category != null && category != rootCategory)
            {
                if (category.ParentCategory != null && category.ParentCategory != rootCategory)
                {
                    <li>
                        @if (string.IsNullOrEmpty(category.ParentCategory.Link))
                        {
                            <a href="@Url.RouteUrl("FrontEndArticleIndex", new { categoryname = StringHelper.StringFilter(category.ParentCategory.Name), categoryid = category.ParentCategory.Id })">@category.ParentCategory.Name</a>
                        }
                        else
                        {
                            <a href="@category.ParentCategory.Link">@category.ParentCategory.Name</a>
                        }
                        <i class="fa fa-angle-right"></i>
                    </li>
                }
            }
            @if (category != null && category != rootCategory)
            {
                <li>
                    <span>@category.Name</span>
                </li>
            }
        </ul>
    </div>
    <div class="clear">
        <div class="category-detail">
            @if (category.Categories != null && category.Categories.Any())
            {
                <ul>
                    @foreach (var item in category.Categories.OrderBy(o => o.OrdinalNumber))
                    {
                        <li>
                            <h2>
                                @if (string.IsNullOrEmpty(item.Link))
                                {
                                    <a href="@Url.RouteUrl("FrontEndArticleIndex", new { categoryName = StringHelper.StringFilter(item.Name), categoryId = item.Id })">@item.Name</a>
                                }
                                else
                                {
                                    <a href="@item.Link">@item.Name</a>
                                }
                            </h2>
                            @{Html.RenderAction("ArticlesByCategory1", "Article", new { categoryId = item.Id });                }
                        </li>
                    }
                </ul>
            }
        </div>
        <div class="right-content">
            @if (rootCategory != null)
            {
                long cat = (category != null && !category.IsNullOrEmpty) ? category.Id : 0;
                @Html.Partial("_RightMenu2", rootCategory, new ViewDataDictionary { { "categoryId", cat } });

            }
            @if (category != null && !category.IsNullOrEmpty)
            {
                Html.RenderAction("MostViewed", "Shared", new { categoryId = category.Id, categoryName = category.Name });
                Html.RenderAction("Featured", "Shared", new { categoryId = category.Id, articleId = -1, category = category.Name });
            }
            else
            {
                if (rootCategory != null && !rootCategory.IsNullOrEmpty)
                {
                    Html.RenderAction("MostViewed", "Shared", new { categoryId = rootCategory.Id, categoryName = rootCategory.Name });
                    Html.RenderAction("Featured", "Shared", new { categoryId = rootCategory.Id, articleId = -1, categoryName = rootCategory.Name });
                }
                else
                {
                    Html.RenderAction("MostViewed2", "Shared");
                }
            }            
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
    jQuery(document).ready(function () {
        var a = 'category_menu_' + '@rootCategory.Id';
        if ('#' + a) {
            $('#' + a).addClass('active');
        }
    });
    </script>
}

Web/Views/Article/Category2.cshtml
@using Common;
@using Entities.Models;
@model IEnumerable<Article>
@{
    Category category = (Category)ViewBag.Category;
    Category rootCategory = (Category)ViewBag.RootCategory;
    ViewBag.Title = category.Name;
    Layout = "~/Views/Shared/_Layout_Category2.cshtml";
    var pagingInfo = (PagingInfo)ViewBag.PagingInfo;
}

<div class="category-header">
    <div class="category-header-detail">
        <img src="@(string.IsNullOrEmpty(rootCategory.DescriptionIcon) ? " />Images/FrontEndV1/img_mainDetail.jpg" : rootCategory.DescriptionIcon)" alt="@rootCategory.Name" title="@rootCategory.Name" />
        @if (rootCategory != null && !rootCategory.IsNullOrEmpty)
        {
            <h2>@rootCategory.Name</h2>
        }
    </div>
</div>
<div class="category-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="@Url.RouteUrl("FrontEndHomeIndex")">Trang chủ</a>
                <i class="fa fa-angle-right"></i>
            </li>
            @if (rootCategory != null)
            {
                <li>
                    @if (string.IsNullOrEmpty(rootCategory.Link))
                    {
                        <a href="@Url.RouteUrl("FrontEndArticleIndex", new { categoryname = StringHelper.StringFilter(rootCategory.Name), categoryid = rootCategory.Id })">@rootCategory.Name</a>
                    }
                    else
                    {
                        <a href="@rootCategory.Link">@rootCategory.Name</a>
                    }
                    <i class="fa fa-angle-right"></i>
                </li>
            }            
            @if (category != null && category != rootCategory)
            {
                if (category.ParentCategory != null && category.ParentCategory != rootCategory)
                {
                    <li>
                        @if (string.IsNullOrEmpty(category.ParentCategory.Link))
                        {
                            <a href="@Url.RouteUrl("FrontEndArticleIndex", new { categoryname = StringHelper.StringFilter(category.ParentCategory.Name), categoryid = category.ParentCategory.Id })">@category.ParentCategory.Name</a>
                        }
                        else
                        {
                            <a href="@category.ParentCategory.Link">@category.ParentCategory.Name</a>
                        }
                        <i class="fa fa-angle-right"></i>
                    </li>
                }
            }            
            @if (category != null && category != rootCategory)
            {
                <li>
                    <span>@category.Name</span>
                </li>
            }
        </ul>
    </div>
    <div class="clear">
        <div class="category-detail">
            <h3>@category.Name</h3>
            @if (Model != null && Model.Any())
            {
                foreach (var item in Model)
                {
                    <div class="clear list1">
                        <p class="pic">
                            <a href="@Url.RouteUrl("FrontEndArticleDetail", new { categoryName = StringHelper.StringFilter(category.Name), title = StringHelper.StringFilter(item.Title), categoryId = category.Id, id = item.Id })">
                                <img alt="" src="@(string.IsNullOrEmpty(item.ImageDescription) ? "http://www.placehold.it/80x63/bdbdbd/AAAAAA&text=No+image" : item.ImageDescription)" title="@item.Title" />
                            </a>
                        </p>
                        <div>
                            <a href="@Url.RouteUrl("FrontEndArticleDetail", new { categoryName = StringHelper.StringFilter(category.Name), title = StringHelper.StringFilter(item.Title), categoryId = category.Id, id = item.Id })" title="@item.Title">
                                @item.Title
                            </a>
                            <p>
                                @if (!string.IsNullOrEmpty(item.Description))
                                {
                                    @Common.CommonHelper.RemoveHtmlTags(item.Description, 300)<span>...</span>
                                }
                            </p>

                        </div>
                    </div>
                }
                
                <div class="navigation">
                    Trang
                    @Html.Raw(Html.pageLinks(pagingInfo.TotalPages, pagingInfo.CurrentPage, x => Url.RouteUrl("FrontEndArticleIndex", new { categoryName = StringHelper.StringFilter(category.Name), categoryId = category.Id, p = x })))
                </div>
            }
        </div>
        <div class="right-content">
            @if (rootCategory != null)
            {
                long cat = (category != null && !category.IsNullOrEmpty) ? category.Id : 0;
                @Html.Partial("_RightMenu2", rootCategory, new ViewDataDictionary { { "categoryId", cat } });

            }
            @if (category != null && !category.IsNullOrEmpty)
            {
                Html.RenderAction("MostViewed", "Shared", new { categoryId = category.Id, categoryName = category.Name });
                Html.RenderAction("Featured", "Shared", new { categoryId = category.Id, articleId = -1, categoryName = category.Name });
            }
            else
            {
                if (rootCategory != null && !rootCategory.IsNullOrEmpty)
                {
                    Html.RenderAction("MostViewed", "Shared", new { categoryId = rootCategory.Id, categoryName = rootCategory.Name });
                    Html.RenderAction("Featured", "Shared", new { categoryId = rootCategory.Id, articleId = -1, categoryName = rootCategory.Name });
                }
                else
                {
                    Html.RenderAction("MostViewed2", "Shared");
                }
            }
        </div>
    </div>
</div>
@section scripts{
<script type="text/javascript">
    jQuery(document).ready(function () {
        var a = 'category_menu_' + '@rootCategory.Id';
        if ('#' + a) {
            $('#' + a).addClass('active');
        }
    });
    </script>
}

Web/Views/Article/Category5.cshtml
@using Entities.Models;
@model IEnumerable<Category>
@{
    Category category = (Category)ViewBag.Category;
    ViewBag.Title = category.Name;
    Layout = "~/Views/Shared/_DetailLayout.cshtml";
}


<div class="topSlider_detail list-category">
    <div class="content_slider_detail">
        <img src="@(string.IsNullOrEmpty(category.DescriptionIcon) ? "/Images/FrontEndV1/bg01.jpg" : category.DescriptionIcon)" alt="@category.Name" title="@category.Name" />
        <h2>@category.Name</h2>
        <h3>@(Html.Raw(category.Description))</h3>
    </div>
</div>
<div class="content full">
    <div class="category">
        <h2>&nbsp;</h2>
        <ul>
            @if (Model != null && Model.Any())
            {
                foreach (var item in Model)
                {
                    <li>
                        <div class="cat-icon">
                            <img src="@(string.IsNullOrEmpty(item.SmallIcon) ? "http://www.placehold.it/70x70/EFEFEF/AAAAAA&text=No+image" : item.SmallIcon)" class="img-responsive" alt="">
                        </div>
                        <div class="text">
                            <h4>
                                @if (string.IsNullOrEmpty(item.Link))
                                { 
                                <a href="@Url.RouteUrl("FrontEndArticleIndex", new { categoryName = Common.StringHelper.StringFilter(item.Name), categoryId = item.Id })">
                                    @item.Name
                                </a>
                                }
                                else
                                {
                                    <a href="@item.Link">@item.Name</a>
                                }
                            </h4>
                            <div>
                                @Html.Raw(item.Description)
                            </div>
                        </div>
                    </li>
                }
            }
        </ul>
        <div class="clear"></div>
    </div>    
    <div class="clear"></div>
    <h2>&nbsp;</h2>
    @{Html.RenderAction("LeftArticle1Category", "Shared");}
    <h2>&nbsp;</h2>
    @{Html.RenderAction("LeftArticle2Category", "Shared");}
</div>
@section scripts{
    <script type="text/javascript">
    jQuery(document).ready(function () {
        var a = 'category_menu_' + '@category.Id';
        if ('#' + a) {
            $('#' + a).addClass('active');
        }
    });
    </script>
}